development:
  adapter: mysql
  database: open_code_analyzer_dev
  username: root
  password: root

test:
  adapter: mysql
  database: open_code_analyzer_test
  username: root
  password: root

production:
  adapter: mysql
  database: open_code_analyzer_prod
  username: root
  password: root